### PR TITLE
onsets_to_dm and Design_Matrix fixes

### PR DESCRIPTION
**Pull request by ejolly**

### CODE REVIEW

**Comment by ejolly** [comment]
@ljchang This should fix https://github.com/cosanlab/nltools/issues/335 and https://github.com/cosanlab/nltools/issues/325 and a few other small bugs + tests.

Also my IDE is showing the following two-lines as unused variables in these files:  

`var_false` in  [analysis.py](https://github.com/cosanlab/nltools/blob/master/nltools/analysis.py#L217)  
`centers` in [simulator.py](https://github.com/cosanlab/nltools/blob/master/nltools/simulator.py#L139)  

Should I remove them in this PR or do those reveal bugs that we missed?

**Comment by ljchang** [comment]
update looks good, let's get tests to pass before we merge.

Let's hold off on removing those last two unused variables. Those are two functions that I've been wanting to refactor.

**Comment by ljchang** [comment]
Looks like everything is passing now, @ejolly ready to merge?

**Comment by ejolly** [comment]
Yup should be good

**Pull request merged**
